Update filtering nbt docs
PaperMC/docs pull request #120
Opened 2022-12-17 17:12 UTC by Machine-Maker

For https://github.com/PaperMC/Paper/pull/6613

2022-12-21 19:33 UTC, MiniDigger commented on docs/paper/admin/reference/world-configuration.md
> +  permission. If a player with that permission places an entity, this filter list will be ignored.
mmh, I feel like this could be better worded. can't we just say, "Players with the blah permission ignore this filter"?

2022-12-28 04:06 UTC, Camotoy commented
OK, so, even I (as someone who knows a bit of Minecraft) had to re-read this a couple times to understand it. But even so - maybe add why I, a server administrator, should care about this setting?

2022-12-28 11:31 UTC, olijeffers0n commented
I agree with Camotoy, I don't think the description does a very good job at all of describing what it does

2023-02-28 08:35 UTC, olijeffers0n commented on docs/paper/admin/reference/world-configuration.md
> +  For example, if `Pos` wasn't included a spawn egg could place an entity at any location.
NitPicky, but you need a comma after included.

2023-02-28 15:17 UTC, kennytv requested changes
nbt "tag(s)" instead of "path(s)" is the standard term used in the community

2023-02-28 15:23 UTC, Machine-Maker commented
> nbt "tag(s)" instead of "path(s)" is the standard term used in the community, including their names

Well the setting itself uses the word `paths` to avoid saying tag twice. Should the description still refer to them as tags?

2023-02-28 15:25 UTC, kennytv commented
A better name for the setting would have been "entity nbt tags", but yeah the description should just say tags to be easier to understand

2023-02-28 15:26 UTC, Machine-Maker commented
> entity nbt tags

would be easily mistaking for NBT tags on entities, which this is not. Its the `EntityTag` tag on ItemStacks

2023-02-28 15:28 UTC, kennytv commented
Oh righ, yeah. the desc should still be changed :p

2023-02-28 15:35 UTC, kennytv approved these changes

2023-02-28 15:45 UTC, olijeffers0n approved these changes

2023-02-28 15:47 UTC, merged