Migration Guides
PaperMC/docs pull request #180
Opened 2023-06-17 22:26 UTC by Owen1212055

Best to wait so we have actual guides finished.

2023-07-07 20:07 UTC, Machine-Maker requested changes

2023-07-07 20:07 UTC, Machine-Maker commented on docs/paper/dev/api/obsolete-migration/adventure.md
> +slug: /dev/adventure
Should be more specific with this slug. Like adding a `migration/` section.

2023-07-07 20:07 UTC, Machine-Maker commented on docs/paper/dev/api/obsolete-migration/material.md
> +slug: /dev/material
Same as above

2023-10-06 08:22 UTC, me4502 commented on docs/paper/dev/api/obsolete-migration/material.md
> +Material was originally built when every single item had a corresponding block.
I don't believe this line is true? There were numerous items that did not have a block equivalent at that point in time. stick, flint, coal, string, most of the non-cake food items, etc

2024-12-29 01:39 UTC, closed without merging