Add Folia Compatibility info to Paper
PaperMC/docs pull request #185
Opened 2023-06-25 11:37 UTC by olijeffers0n

WIP. Currently only includes info on the schedulers. Please let me know about the other topics that should be covered

2023-06-25 11:41 UTC, powercasgamer requested changes

2023-06-25 11:41 UTC, powercasgamer commented on docs/paper/dev/api/folia-support.md
> +GlobalRegionScheduler globalScheduler = server.getGlobalRegionScheduler();
imo only one of these is needed
```suggestion

```

2023-06-25 11:41 UTC, powercasgamer commented on docs/paper/dev/api/folia-support.md
> +AsyncScheduler asyncScheduler = server.getAsyncScheduler();
same here
```suggestion

```

2023-06-25 11:41 UTC, powercasgamer commented on docs/paper/dev/api/folia-support.md
> +
```suggestion
```

2023-06-25 11:41 UTC, powercasgamer commented on docs/paper/dev/api/folia-support.md
> +use this utility method to check if the current server is running folia:
```suggestion
use this utility method to check if the current server is running Folia:
```

2023-08-25 11:47 UTC, kennytv requested changes

2023-08-25 11:47 UTC, kennytv commented on docs/paper/dev/api/folia-support.md
> +which will follow it across regions. As an example, Let's say I want to set a block as beehive:
```suggestion
which will follow it across regions. As an example, let's say I want to set a block to a beehive:
```

2023-08-25 11:47 UTC, kennytv commented on docs/paper/dev/api/folia-support.md
> +In order to support Paper and Folia, you must use the correct scheduler. Folia has many different type of schedulers
```suggestion
In order to support Paper and Folia, you must use the correct scheduler. Folia has different types of schedulers 
```

2023-08-25 11:47 UTC, kennytv commented on docs/paper/dev/api/folia-support.md
> +When using these schedulers when running on Paper, they will be internally handled to provide the same functionality as if you were
as if?

2023-08-27 16:49 UTC, olijeffers0n commented
Addressed comments and merged main

2023-08-28 11:11 UTC, kennytv approved these changes

2023-08-28 12:22 UTC, merged