Add docs for i18n in paper
PaperMC/docs pull request #194
Opened 2023-07-08 01:02 UTC by Machine-Maker

part of https://github.com/PaperMC/docs/issues/190

2023-07-08 09:07 UTC, kennytv reviewed
Also needs at least a short code example

2023-07-08 09:07 UTC, kennytv commented on docs/paper/dev/api/component-api/i18n.md
> +appeal to the largest userbase. Paper and Adventure make this simply by adding a server-side
```suggestion
appeal to the largest userbase. Paper and Adventure make this simple by adding a server-side
```

2023-07-08 09:07 UTC, kennytv commented on docs/paper/dev/api/component-api/i18n.md
> +The player's language as declared in the settings packet sent by the client arrives **after** the player has joined the server, so there are no guarentees that
```suggestion
The player's language as declared in the settings packet sent by the client arrives **after** the player has joined the server, so there are no guarantees that
```

2023-07-08 09:07 UTC, kennytv commented on docs/paper/dev/api/component-api/i18n.md
> +Vanilla minecraft handles translations on the client by using the language files bundled with the client or provided via resource packs. If you don't want to send custom language files
```suggestion
Vanilla Minecraft handles translations on the client by using the language files bundled with the client or provided via resource packs. If you don't want to send custom language files
```

2023-07-09 00:09 UTC, Machine-Maker commented
Ok, added an example using `ResourceBundle`. Do we need to add an example of a custom `Translator` implementation? I don't really think its needed.

2023-07-09 00:46 UTC, olijeffers0n commented on docs/paper/dev/api/component-api/i18n.md
> +registry.registeryAll(Locale.US, bundle, true);
`registeryAll` -> `registerAll`

2023-07-09 01:06 UTC, olijeffers0n commented
As someone who hasn't used translatable components before, I would want an example of how to send these / create these components. Also, an explanation to what a translation key and/or what the translation files look like.

2023-07-09 15:16 UTC, xpple commented on docs/paper/dev/api/component-api/i18n.md
> +chat, entity display names, scoreboards, tab lists, etc. all support translations.
It is correct English.

2023-07-09 15:19 UTC, Lulu13022002 commented on docs/paper/dev/api/component-api/i18n.md
> +chat, entity display names, scoreboards, tab lists, etc. all support translations.
Indeed

2023-07-09 17:35 UTC, Machine-Maker commented on docs/paper/dev/api/component-api/i18n.md
> +chat, entity display names, scoreboards, tab lists, etc. all support translations.
Actually, I think its supposed to have a comma after it if its used in the middle of a sentence. So I'll change it to `...tab lists, etc., all support...`

2023-07-09 17:51 UTC, Machine-Maker commented
> As someone who hasn't used translatable components before, I would want an example of how to send these / create these components. Also, an explanation to what a translation key and/or what the translation files look like.

Good call. We can talk about the `Translatable` interface here, and all the api types that implement that.

As for an example of a resource bundle file... that is just one implementation. You can create translations from any format you want, its not closed off.

2023-08-13 11:00 UTC, olijeffers0n requested changes
Looks good, the only thing I would say is that it probably needs an example of using a translatable component

2023-08-13 20:30 UTC, olijeffers0n approved these changes
Looks good to me

2023-08-13 20:30 UTC, merged