Plugin messaging Docs
PaperMC/docs pull request #196
Opened 2023-07-13 11:22 UTC by olijeffers0n

This takes the content of #84 and supersedes it. That PR has been abandoned and this is a topic that comes up frequently. 

Please let me know if any of the technical details are incorrect :)

2023-07-13 12:26 UTC, kennytv commented on docs/paper/dev/api/plugin-messaging.md
> +will be sending on any given plugin channel. You'll should to do this alongside your other event listener registrations.
```suggestion
First, we're going to take a look at your Paper server. Your Paper server plugin will need to register that it 
will be sending on any given plugin channel. You should to do this alongside your other event listener registrations.
```

2023-07-13 12:26 UTC, kennytv commented on docs/paper/dev/api/plugin-messaging.md
> +Then, it recognized the channel as it's own, and in alignment with BungeeCord's format sent our player to the `hub2` server.
```suggestion
Then, it recognized the channel as its own and in alignment with BungeeCord's format sent our player to the `hub2` server.
```

2023-07-13 12:26 UTC, kennytv commented on docs/paper/dev/api/plugin-messaging.md
> +Although we sent a `Connect` message to the proxy there are a few other cases that proxies will act on.
```suggestion
Although we sent a `Connect` message to the proxy, there are a few other cases that proxies will act on. 
```

2023-07-13 12:35 UTC, kennytv approved these changes

2023-07-13 12:40 UTC, lynxplay commented on docs/paper/dev/api/plugin-messaging.md
> +##### Example: `Forward`
Would it be useful to at least throw some bare bone "what exactly are you trying to do" text here?
It obviously can be understood by *reading* the code below, however these docs are meant for developers learning this. It hence might be useful to give them a heads up as to what these examples try to accomplish.

2023-07-13 13:59 UTC, the456gamer reviewed
1 thing i noticed while looking at the deploy preview

2023-07-13 14:01 UTC, olijeffers0n commented on docs/paper/dev/api/plugin-messaging.md
> +:::tip[The "bungeecord" and "bungeecord:main" channel]
Yikes, that seems like a bit of a bug on docosaurus’ part tbh. I’d imagine it’s cause it’s looking for the colons to end the admonition, but thanks!

2023-07-16 13:24 UTC, olijeffers0n commented
Added a note to the forward example

2023-07-16 14:34 UTC, lynxplay requested changes

2023-07-16 14:34 UTC, lynxplay commented on docs/velocity/dev/how-to/plugin-messaging.md
> +
Useless empty line.

2023-07-16 14:34 UTC, lynxplay commented on docs/paper/dev/api/plugin-messaging.md
> +:::caution[Example of banning a player on all servers]
I feel like, we'd wanna move this like, behind the following example.
Reading this had me think that the following example was for banning players.

2023-07-16 14:34 UTC, lynxplay commented on docs/velocity/dev/how-to/plugin-messaging.md
> +First introduced in [2012](https://web.archive.org/web/20220711204310/https://dinnerbone.com/blog/2012/01/13/minecraft-plugin-channels-messaging/),
Do we want to mention somewhere that it is bungeecord:main on the proxy side but BungeeCord on the server side ?

2023-07-16 15:16 UTC, lynxplay approved these changes

2023-07-16 15:17 UTC, merged

2023-07-17 15:25 UTC, Lulu13022002 commented on docs/paper/dev/api/plugin-messaging.md
> +| `PlayerCount`     | Returns the number of players on the specified server. | `server name`                                                    | `server name`, player count`                      |
The player count in the last column doesn't seems well formatted