Clarify classloader isolation section on relocation
PaperMC/docs pull request #203
Opened 2023-07-23 14:21 UTC by A248

The classloader isolation currently implemented does not prevent non-paper plugins from accessing paper plugins' classloaders. As a result, relocation remains a good practice to prevent conflicts with non-paper plugins.

This PR is far more limited in scope than #183

2023-07-23 14:33 UTC, Machine-Maker approved these changes

2023-07-23 14:43 UTC, olijeffers0n requested changes
Looks good, just one tweak

2023-07-23 14:43 UTC, olijeffers0n commented on docs/paper/dev/getting-started/paper-plugins.md
> +to your ``paper-plugin.yml``. Note, other paper plugins will still be unable to access your classloader.
```suggestion
to your ``paper-plugin.yml``. Note, other Paper plugins will still be unable to access your classloader.
```

2023-07-24 07:26 UTC, olijeffers0n approved these changes

2023-08-06 01:10 UTC, lynxplay approved these changes

2023-08-06 01:10 UTC, merged