Add missing plugin messaging channel
PaperMC/docs pull request #208
Opened 2023-08-05 19:34 UTC by olijeffers0n

Adds `MessageRaw `with component example

2023-08-05 20:58 UTC, Nacioszeczek commented
Perhaps using a JSON component serializer would be way cleaner than the JSON itself?

2023-08-06 07:18 UTC, MiniDigger commented
yeah, really dont wanna encourage hard coding json strings in any way

2023-08-06 11:18 UTC, olijeffers0n commented
Yeah we discussed this last night. Updated it to use adventure

2023-08-07 11:23 UTC, MiniDigger approved these changes

2023-08-11 19:32 UTC, NoahvdAa requested changes

2023-08-11 19:32 UTC, NoahvdAa commented on docs/paper/dev/api/plugin-messaging.md
> +        out.writeUTF("ALL");
The text above the snippet make it sound like this is only going to one player, when this is being broadcasted to all players on the proxy. This should be clarified to mention that this should be the name of the target player or ALL.

2023-08-11 19:32 UTC, NoahvdAa commented on docs/paper/dev/api/plugin-messaging.md
> +or messages with hover events.
Maybe also mention sending to players that aren't on the same backend server as an extra use case.

2023-08-11 20:27 UTC, olijeffers0n commented
Thanks, Addressed comments

2023-08-11 22:17 UTC, NoahvdAa commented
Now that I think of it, "This is useful for sending clickable messages to players," sounds weird considering we (and Spigot) have native support for chat components. I feel like this might be a leftover in the bungee docs from a time where this native integration didn't exist yet. Maybe we're better off removing this entire part? I don't really see the purpose for this channel anymore apart from the aforementioned option of using it to send messages to players on a different server.

2023-08-12 10:37 UTC, olijeffers0n commented
Good point. I think this is more just bad wording...  but yeah the fact that it is a clickable component is not really significant anymore.

2023-08-12 12:02 UTC, NoahvdAa approved these changes

2023-08-12 12:03 UTC, merged