Add comparison matrix to Velocity comparison page
PaperMC/docs pull request #222
Opened 2023-08-20 21:59 UTC by Malfrador

A question that gets asked often is "Should I use Velocity, Waterfall or BungeeCord". While the existing page already answer that, its a lot to read and contains plenty of details that most server owners just looking for a simple answer aren't interested in.

This PR adds a small markdown table with a comparison matrix to the top of that doc page. It makes it easy to see at a glance what Velocity does, and what it doesn't do - mainly, supporting plugins made for BungeeCord, another question that gets asked very often. 

![chrome_PdzuRM5Us1](https://github.com/PaperMC/docs/assets/6106558/3ea81232-2aeb-4635-a0ac-77dbf6416531)

Goal of this PR is to have an easy to understand overview for someone just looking for a simple answer to the aforementioned question. Those interested in more in-depth information can just continue reading the docs page.

2023-08-20 22:14 UTC, Nacioszeczek requested changes

2023-08-20 22:14 UTC, Nacioszeczek commented on docs/velocity/admin/reference/comparison.md
> +| API supporting modern Minecraft features | ❌          | ❌         | ✅        |
Could list some of the stuff, e.g. Adventure support

2023-08-20 22:14 UTC, Nacioszeczek commented on docs/velocity/admin/reference/comparison.md
> +| Improved mod support                     | ❌          | ❌         | ✅        |
Should probably mention modern Forge being problematic, on all proxies though

2023-08-20 22:14 UTC, Nacioszeczek commented on docs/velocity/admin/reference/comparison.md
> +| BungeeCord plugins                       | ✅          | ✅         | ❌        |
It is somewhat possible to run Bungee plugins on Velocity using a plugin, not sure if that's reliable enough to mention that on the docs though

2023-08-20 22:15 UTC, olijeffers0n commented
Two rows for velocity and bungee plugins seem redundant but i can’t think of a better way to do this. Also, surely there must be another pro to Bungee over velocity? Seems rather one sided that’s all 😄

2023-08-21 07:14 UTC, MiniDigger commented
that table should somehow also show a difference between bungee and waterfall (not that I would know something to add there, lol)

2023-08-25 12:24 UTC, A248 commented
If you haven't any differences between BungeeCord and Waterfall, or you aren't willing to document them, you may want to remove one of the columns entirely.

There are differences. Waterfall guarantees Slf4j and exposes it in the API. On BungeeCord this library happens to be provided, but only due to the recent circumstance of library loading. Moreover, Waterfall has miscellaneous performance improvements to the implementation. I believe there might be a few new events. If we can get https://github.com/PaperMC/Waterfall/pull/812 merged, then we can also say BungeeCord doesn't address some thread safety bugs -- which would be true.

By the way, Velocity can run some BungeeCord plugins via [Snap](https://github.com/Phoenix616/Snap). You may want to consider, thus, a mixed marker between a checkmark and an X.

Finally, in Velocity's favor, I strongly suggest adding a "Recommended by A248" row to your comparison matrix.

2023-09-10 20:16 UTC, olijeffers0n requested changes

2023-09-10 20:16 UTC, olijeffers0n commented on docs/velocity/admin/reference/comparison.md
> +| Resource efficient					   | ❌         | ✅        | ✅✅     |
Tabs not spaces

2023-09-10 20:16 UTC, olijeffers0n commented on docs/velocity/admin/reference/comparison.md
> + Snap is not maintained by the Velocity project._
```suggestion
 Snap is not maintained by, or affiliated with, the Velocity project._
```

2023-09-10 20:24 UTC, olijeffers0n approved these changes

2023-09-10 20:31 UTC, Nacioszeczek approved these changes

2023-09-10 20:36 UTC, Warriorrrr approved these changes

2023-09-10 20:37 UTC, merged