Add paper contribution docs for events
PaperMC/docs pull request #226
Opened 2023-08-25 01:40 UTC by Machine-Maker

2023-08-25 08:18 UTC, olijeffers0n requested changes
Few Changes

2023-08-25 08:18 UTC, olijeffers0n commented on docs/paper/contributing/events.md
> +There are several requirements for events in the Paper API. Note that while not all existing events may follow these
this is the bit that shows up in the embed. Maybe make a slightly more user friendly sentence for this, move this down and the note could even go in an amondition

2023-08-25 08:18 UTC, olijeffers0n commented on docs/paper/contributing/events.md
> +* [Mutability](#mutability)
Maybe requires more than one word. this looks off

2023-08-25 08:18 UTC, olijeffers0n commented on docs/paper/contributing/events.md
> +
Extra newline

2023-08-25 08:18 UTC, olijeffers0n commented on docs/paper/contributing/events.md
> +
Why double new lines?

2023-08-25 18:56 UTC, olijeffers0n commented
Your .editorconfig has made it in somehow, also need to look at the redirect to check it. Otherwise the content looks generally good

2023-08-25 19:11 UTC, Machine-Maker commented
oh editorconfig should be in, but I guess it can be a different PR.

2023-08-25 23:15 UTC, olijeffers0n approved these changes
I’ve looked over the sidebar config and all looks good. Content of the page is good for now and can be added to in the future as needed. Up to you, but i’m happy for this editorconfig to stay here

2023-08-27 16:30 UTC, NotMyFault approved these changes

2023-08-27 16:30 UTC, merged