Add faq page and java version check info
PaperMC/docs pull request #240
Opened 2023-09-08 14:45 UTC by MiniDigger

https://github.com/PaperMC/Paper/pull/9692

2023-09-08 14:46 UTC, Warriorrrr commented on config/sidebar.paper.ts
> -            "admin/how-to/basic-troubleshooting",
Should probably not be removed

2023-09-08 14:50 UTC, olijeffers0n commented on docs/paper/admin/reference/system-properties.md
> +- **description**: Allows you to bypass the java version check. See [this](/paper/misc/faq) for more info.
Direct link with anchor is probably more useful here?

2023-09-08 14:51 UTC, olijeffers0n commented on docs/paper/admin/misc/faq.md
> +
Double empty lines

2023-09-08 14:57 UTC, olijeffers0n requested changes

2023-09-08 14:57 UTC, olijeffers0n commented on docs/paper/admin/misc/faq.md
> +Unsupported early-access or internal versions of Java are often missing features, have known issues or be straight up broken.
```suggestion
Unsupported, early-access, or internal versions of Java are often missing features, have known issues or be straight up broken. 
```

2023-09-08 14:57 UTC, olijeffers0n commented on docs/paper/admin/misc/faq.md
> +If you still wish to continue, knowing that you are on your own and will receive NO support, you can disable the check a system property, as explained [here](/paper/reference/system-properties#paperi
```suggestion
If you still wish to continue, knowing that you are on your own and will receive NO support, you can disable the check, a system property, as explained [here](/paper/reference/system-properties#paperignorejavaversion).
```

2023-09-08 14:57 UTC, olijeffers0n commented on docs/paper/admin/reference/system-properties.md
> +- **description**: Allows you to bypass the java version check. See [this](/paper/misc/faq#unsupported-java-detected-what-do-i-do) for more info.
```suggestion
- **description**: Allows you to bypass the java version check. See [here](/paper/misc/faq#unsupported-java-detected-what-do-i-do) for more info.
```

2023-09-08 16:48 UTC, Nacioszeczek commented on docs/paper/admin/reference/system-properties.md
> +- **description**: Allows you to bypass the java version check. See [here](/paper/faq#unsupported-java-detected-what-do-i-do) for more info.
`Java` would look better than `java`

2023-09-09 20:28 UTC, olijeffers0n approved these changes

2023-09-09 20:30 UTC, merged