add compression-level description
PaperMC/docs pull request #242
Opened 2023-09-12 14:09 UTC by Leguan16

This adds the necessary description for the new `compression-level` config option in `config/paper-global.yml`

See https://github.com/PaperMC/Paper/pull/9711

2023-09-12 14:14 UTC, Nacioszeczek commented
Waiting for the changes to be merged into Paper

2023-09-12 16:26 UTC, olijeffers0n requested changes
Blocking for paper merge. Also, can you doc what the default value is please? In the description that is please ☺️

2023-09-12 16:29 UTC, Leguan16 commented
well, i checked if default values in the other places (where IntOr is used) are present and they aren't so I did not include it here as well for consistency.

2023-09-12 16:35 UTC, lynxplay commented
Not that -1 would be of much use to the docs. The default is up to the deflate impl

2023-09-12 17:35 UTC, Leguan16 commented
> Not that -1 would be of much use to the docs. The default is up to the deflate impl

does that mean that including the value is unnecessary or not?

2023-09-12 17:43 UTC, lynxplay commented
Can include the -1 being default, just you need to also explain that -1 means the compression will choose a sensible compression level.

2023-09-12 21:41 UTC, Leguan16 commented
> Can include the -1 being default, just you need to also explain that -1 means the compression will choose a sensible compression level.

Should I also mention that Paper is using the velocity compressor and that the default is 6?

2023-09-12 21:56 UTC, olijeffers0n commented
Personally i would say yes, as it gives people something to use as a reference to their values as well.

2023-09-12 22:22 UTC, Leguan16 commented
I hope this makes sense lol

2023-09-12 22:31 UTC, olijeffers0n commented
Yeah looks ok 👌

2023-09-13 18:54 UTC, powercasgamer commented on docs/paper/admin/reference/configuration/global-configuration.mdx
> +    description: 'A higher compression level means less data transmitted for the cost of more CPU time.
```suggestion
    description: 'A higher compression level means less data transmitted at the cost of more CPU time.
```

2023-09-13 19:25 UTC, Leguan16 commented
changed

2023-09-14 06:54 UTC, powercasgamer approved these changes

2023-09-14 11:02 UTC, lynxplay approved these changes

2023-09-14 11:11 UTC, merged