Add initial docs for Entity Pathfinders and Mob Goal API
PaperMC/docs pull request #289
Opened 2024-01-24 22:26 UTC by olijeffers0n

I have not extensively used either of these API's in the past, however these seem to work

2024-01-25 00:58 UTC, Machine-Maker commented on docs/paper/dev/api/entity-pathfinder.md
> +The pathfinder is only available for Mobs, not for all entities.
Clarify that this is for entities that implement `Mob`.

2024-01-27 10:38 UTC, MiniDigger commented on docs/paper/dev/api/entity-pathfinder.md
> +- `setCanOpenDoors(boolean)`: Whether the entity can open doors.
`open` is a bit ambiguous here as iirc it refers to both villagers opening doors or zombies breaking doors, it basically makes the pathfinder consider wodden doors as open I guess? (didnt check code)

2024-01-27 10:39 UTC, MiniDigger commented on docs/paper/dev/api/mob-goals.md
> +They are specific to each mob type, so you can't use a cow goal on a zombie for example.
an example would be nice I guess?

2024-01-27 10:41 UTC, MiniDigger commented on docs/paper/dev/api/mob-goals.md
> +## Stopping a Goal
I wouldn't call this heading stopping but removing

2024-01-27 10:42 UTC, MiniDigger commented
this needs notes on how vanilla selects which goals to activate and prolly some more caveats on how pathfinding works from somebody who actually uses the pathfinder, iirc it can ge all kinda wonky to call moveTo every tick.

2024-04-06 21:58 UTC, powercasgamer requested changes

2024-04-06 21:58 UTC, powercasgamer commented on docs/paper/dev/api/mob-goals.md
> +        player.sendMessage(text("I Stopped following you!"));
```suggestion
        player.sendMessage(text("I stopped following you!"));
```

2024-04-06 21:58 UTC, powercasgamer commented on docs/paper/dev/api/entity-pathfinder.md
> +If we want to access the current Path for the cow, we can call `getCurrentPath()` on the pathfinder:
```suggestion
If we want to access the current path for the cow, we can call `getCurrentPath()` on the pathfinder:
```

2024-10-14 15:46 UTC, Lulu13022002 commented on docs/paper/dev/api/entity-pathfinder.md
> +You can call `stopPathfinding()` on the pathfinder to stop the pathfinder. This will stop the pathfinder and clear the
This seems a bit redundant

2024-10-14 15:46 UTC, Lulu13022002 commented on docs/paper/dev/api/mob-goals.md
> +description: A guide to the PDC API for storing data.
This is wrong

2024-10-14 15:46 UTC, Lulu13022002 commented on docs/paper/dev/api/mob-goals.md
> +    public @NotNull GoalKey<Camel> getKey() {
I think you can remove the NotNull annotations it's better to assume types are not null by default

2025-07-09 15:21 UTC, Phoenix616 commented on docs/paper/dev/api/mob-goals.md
> +:::
This feels confusing as it kinda reads as if one could add Vanilla goals to entities (especially under the `addGoal` example) which isn't possible right now.

2025-11-15 23:42 UTC, zlataovce approved these changes
the casing is a bit wonky in several places beyond my comments, but otherwise lgtm

2025-11-15 23:42 UTC, zlataovce commented on src/content/docs/paper/dev/api/entity-api/mob-goals.md
> +## Creating a Custom Goal
```suggestion
## Creating a custom Goal
```

2025-11-15 23:42 UTC, zlataovce commented on src/content/docs/paper/dev/api/entity-api/entity-pathfinder.md
> +## Pathfinding Rules
```suggestion
## Pathfinding rules
```

2025-11-16 00:10 UTC, Phoenix616 commented
As far as I'm aware of that's just the grammatical rules of titles in English. Basically everything but "a", "the", etc. should be uppercase if I'm not mistaken?

See [Title case](https://en.wikipedia.org/wiki/Title_case) (but Wikipedia itself doesn't use that but sentence casing, which imo. Is easier to read but can feel unnatural in headings)

2025-11-16 09:41 UTC, zlataovce commented
> As far as I'm aware of that's just the grammatical rules of titles in English. Basically everything but "a", "the", etc. should be uppercase if I'm not mistaken?
> 
> See [Title case](https://en.wikipedia.org/wiki/Title_case) (but Wikipedia itself doesn't use that but sentence casing, which imo. Is easier to read but can feel unnatural in headings)

we use sentence case in most places throughout the site

2026-04-25 20:16 UTC, Strokkur424 approved these changes

2026-04-25 20:18 UTC, merged