Improve Start Script Generation for Windows
PaperMC/docs pull request #335
Opened 2024-03-31 21:26 UTC by notTamion

adds an @echo off in front of all windows scripts and adds a pause statement after if auto restart is disabled. This is because people on windows tend to double click the start.bat instead of opening a terminal and running the script from there, which causes the terminal to close when the server stops without giving the user the option to look at e.g. crash logs, i have noticed a lot of people on the discord server just saying "my server stops without any crash log" because of this exact reason.

2024-03-31 21:35 UTC, DerEchtePilz commented
As a suggestion/question, would it make sense to put the pause statement behind a toggle that by default is turned on?

2024-03-31 21:40 UTC, notTamion commented
i didn't look into the component too much but as it looks to me that would require moving stuff around a lot so we can have different toggles for windows and linux. since i am very sure 90+% windows folks are gonna double click it i don't see much reason to have a toggle here.

2024-03-31 21:43 UTC, DerEchtePilz commented
I guess that's fair. I don't use the script generator anyway, and also didn't expect that much more work for a toggle so you have my approval (not that you need it, anyway)

2024-03-31 21:54 UTC, zlataovce approved these changes

2024-03-31 22:32 UTC, olijeffers0n requested changes

2024-03-31 22:32 UTC, olijeffers0n commented on src/components/StartScriptGenerator.tsx
> +  if (platform === "windows") content = "@echo off\n\n" + content;
```suggestion
  if (platform === "linux") {
   content = "#!/bin/bash\n\n" + content;
  } else {
    content = "@echo off\n\n" + content;
  }
```

I would rather do this like this, or with a ternary. Up to you :)

2024-04-01 07:32 UTC, notTamion commented
i know this is technically completely out of scope for this pr (but opening a pr for this small thing is eeh) but shouldn't we have the gen add "nogui" instead of "--nogui" that way it will also work on older versions

2024-04-02 12:16 UTC, olijeffers0n commented
> i know this is technically completely out of scope for this pr (but opening a pr for this small thing is eeh) but shouldn't we have the gen add "nogui" instead of "--nogui" that way it doesn't crash on older versions

Yes, we should. Feel free to add that to this PR if you would like, and I will rename the commit on merge

2024-04-02 17:51 UTC, olijeffers0n approved these changes

2024-04-02 17:52 UTC, merged