New Paper Built-in Commands page
PaperMC/docs pull request #348
Opened 2024-04-08 21:01 UTC by PetarMc1

TODO:
Write info for these commands:
`/paper fixlight`
`/paper mobcaps`
`/paper playermobcaps`

2024-04-09 00:28 UTC, granny commented on .gitignore
revert this file change

2024-04-10 08:24 UTC, powercasgamer requested changes

2024-04-10 08:24 UTC, powercasgamer commented on docs/paper/admin/reference/assets/example-item-dump.png
Use the vanilla resource pack and font.

2024-04-10 08:24 UTC, powercasgamer commented on docs/paper/admin/reference/built-in-commands.md
> +This command requires the `-Dpaper.debug-sync-loads=true` startup flag.
Link to the [docs page](https://docs.papermc.io/paper/reference/system-properties#paperdebug-sync-loads) about this system property

2024-04-10 08:24 UTC, powercasgamer commented on docs/paper/admin/reference/built-in-commands.md
> +It contains many subcommands.
Needs a better description

2024-04-10 08:24 UTC, powercasgamer commented on docs/paper/admin/reference/built-in-commands.md
> +When executed it dumps shows info for a specified entity (or all entities) in a specific world.
```suggestion
When executed it shows info for a specific entity (or all entities) in the specified world.
```
Something like this

2024-04-10 08:24 UTC, powercasgamer commented on docs/paper/admin/reference/built-in-commands.md
> +The heap dump contains detailed information about your server, which can is sensitive.
```suggestion
The heap dump contains detailed information about your server, which can be sensitive.
```

2024-04-10 08:24 UTC, powercasgamer commented on docs/paper/admin/reference/built-in-commands.md
> +Dumps info about the item that the player is holding. It can only be used by plyers!
```suggestion
Dumps info about the item that the player is holding. Can only be used by players!
```

2024-04-11 12:25 UTC, olijeffers0n requested changes

2024-04-11 12:25 UTC, olijeffers0n commented on docs/paper/admin/reference/built-in-commands.md
> +slug: /reference/built-in-commands
Needs a description

2024-04-11 13:04 UTC, PetarMc1 commented on docs/paper/admin/reference/built-in-commands.md
> +slug: /reference/built-in-commands
Wdym

2024-08-23 14:05 UTC, closed without merging