Add page documenting vanilla command permissions
PaperMC/docs pull request #354
Opened 2024-04-21 05:45 UTC by pontaoski

Fixes #340.

2024-04-21 06:33 UTC, zlataovce commented on docs/paper/admin/reference/vanilla-command-permissions.mdx
> +description: Vanilla Minecraft commands and their associated permissions
```suggestion
description: Vanilla Minecraft commands and their associated permissions.
```

2024-04-21 06:33 UTC, zlataovce commented on docs/paper/admin/reference/vanilla-command-permissions.mdx
> +The following is a list of permissions for vanilla commands.
```suggestion
The following is a list of permissions for Vanilla commands.
```

2024-04-21 06:33 UTC, zlataovce commented on docs/paper/admin/reference/vanilla-command-permissions.mdx
> +import { commands } from '@site/src/components/MinecraftCommands'
```suggestion
import React from "react";
import { commands } from "@site/src/components/MinecraftCommands";
```

2024-04-21 06:33 UTC, zlataovce commented on src/components/MinecraftCommands.ts
> +type CommandData = [string, string[], number | string];
this should rather be an interface with properly named properties, looks a little confusing without description

2024-04-21 06:33 UTC, zlataovce commented on src/components/MinecraftCommands.ts
should probably be moved into a different directory, there's no component in the file

2024-04-21 20:14 UTC, olijeffers0n approved these changes

2024-04-21 20:17 UTC, olijeffers0n requested changes
Check Vercel Comments Please

2024-04-22 02:39 UTC, pontaoski commented
the vercel comments aren't public

2024-04-22 22:16 UTC, olijeffers0n commented
> the vercel comments aren't public

Some table cells need restyling to avoid wrap

2024-04-23 10:28 UTC, olijeffers0n approved these changes

2024-04-23 10:28 UTC, merged