feat: add item converter tool, link to minimessage viewer
PaperMC/docs pull request #358
Opened 2024-04-21 17:40 UTC by MiniDigger

2024-04-21 17:53 UTC, zlataovce commented on docs/misc/tools/item-command-converter.mdx
> +description: A tool to update commands from the old nbt based item format to item components
```suggestion
description: A tool to update commands from the old NBT-based item format to item components.
```

2024-04-21 17:53 UTC, zlataovce commented on docs/misc/tools/minimessage-web-editor.md
> +description: A web-based editor for creating and previewing MiniMessage-formatted text.
the front matter title could exclude the heading's parentheses, looks a little nicer on the sidebar
```suggestion
title: MiniMessage Web Editor
description: A web-based editor for creating and previewing MiniMessage-formatted text.
```

2024-04-21 18:27 UTC, Leguan16 reviewed
Maybe move the tools section all the way down to the bottom?

2024-04-21 18:27 UTC, Leguan16 commented on docs/misc/tools/index.mdx
> +# Misc
```suggestion
# Tools
```

2024-04-21 20:07 UTC, olijeffers0n commented
> Maybe move the tools section all the way down to the bottom?

It is standard for us to put categories at the top

2024-04-21 21:23 UTC, kennytv requested changes
Just to make sure this isn't merged early: Needs to wait on more backend changes + it should get a dropdown for switching from the default `Command` to `Item argument` and `Component argument` with their different endpoints

2024-04-22 22:14 UTC, Machine-Maker requested changes

2024-04-22 22:14 UTC, Machine-Maker commented on src/components/ItemCommandConverter.tsx
> +          placeholder="Enter your pre 1.20.5 command here..."
Should specify exactly 1.20.4. Afaik, the convert is only converting from 1.20.4 to 1.20.5, not < 1.20.5 to 1.20.5

2024-05-03 11:21 UTC, olijeffers0n approved these changes

2024-05-03 16:12 UTC, merged