Flatten the Paper development hierarchy
PaperMC/docs pull request #359
Opened 2024-04-21 18:28 UTC by pontaoski

This makes the content more immediately accessible and easier to browse through. Styling has also been adjusted as necessary to accomodate a flatter hierarchy of items; presenting content as a list with headers instead of a grid of cards.

ATM, the hierarchy of other stuff isn't flattened; I can do that if y'all like how it looks on the Paper dev pages.

<table>
<tr>
 <td> before
 <td> after
<tr>
 <td> <img src="https://github.com/PaperMC/docs/assets/20326855/d0fda13f-4bc3-4734-a9a5-3b508f5f80fb"/>
 <td> <img src="https://github.com/PaperMC/docs/assets/20326855/3094dccf-eb9c-4498-81f4-706c80fb361e"/>
</table>

2024-04-21 18:56 UTC, zlataovce commented on docs/paper/dev/api/README.mdx
the `README.mdx` files are needed to not void existing links; they need to be kept or a redirect needs to be set up

2024-04-21 20:09 UTC, olijeffers0n commented on docs/paper/dev/api/README.mdx
I'm not sure this is true - could you clarify?

2024-04-21 20:13 UTC, olijeffers0n requested changes
In addition to the Doc Cards being weird on main admin/dev/contrib pages, I find it weird that the "Welcome to the paper docs" at the top of sidebars have a doc icon as well. Overall, I am a fan of the style though! thanks

2024-04-22 02:37 UTC, pontaoski commented on docs/paper/dev/api/README.mdx
redirects added

2024-04-22 02:37 UTC, pontaoski commented
> In addition to the Doc Cards being weird on main admin/dev/contrib pages, I find it weird that the "Welcome to the paper docs" at the top of sidebars have a doc icon as well. Overall, I am a fan of the style though! thanks

fixed this

2024-07-20 21:26 UTC, olijeffers0n commented
Could this be updated? If you are not able to, do not worry.

2024-12-28 20:19 UTC, olijeffers0n approved these changes
Approved from a technical and feature POV. Help wanted for if this is better than the current sidebar

2024-12-28 22:36 UTC, Machine-Maker commented
Looks good. I still want to do the thing where the "Development", "Admin" things are on the top of the page and you change between projects by the logo/project name however.

But this still works with that, making the whole sidebar just development

2024-12-29 12:44 UTC, zlataovce commented
I'm not sure if the sidebar icons add any value to the navigation experience, it just seems like visual clutter to me; maybe make them a little smaller and darker (to make the page/section names stand out more)?

visual bug when page names are wrapped (icons are shrunk)
<img width="311" alt="image" src="https://github.com/user-attachments/assets/9893d1b0-62c0-4ad5-8069-eb6295af4176" />

light mode makes the sidebar icons blend in with the background completely

2025-04-19 07:51 UTC, zlataovce commented
superseded by #560

2025-04-19 07:51 UTC, closed without merging