refactor: Merge vanilla default files with normal config files
PaperMC/docs pull request #463
Opened 2024-08-13 01:09 UTC by Leguan16

I do not like the current solution to the "how-to vanilla" page. Thats why I am proposing a refactor that merges the two files with adding a `vanilla` field to config options that alter the vanilla behavior. 

```yml
only-merge-items-horizontally:
  vanilla: "true"
  default: "false"
  description: >-
    Prevents merging items that are not on the same y level, preventing potential
    visual artifacts.
```

I am aware of the unnecessary nodes showing no default value. Unfortunately, I did not yet find a way to get rid of them without major refactoring of already existing code. If you have suggestions, please share!

2025-01-03 16:29 UTC, Leguan16 commented
should be open for reviews now!

2025-01-14 14:57 UTC, olijeffers0n requested changes
I like this implementation a lot more, thanks! One thing, could you please rename this `vanilla` within the ConfigDocBlock to something more like `showVanillaValue` or something slightly more self explanatory. Good to merge then

2025-01-14 15:07 UTC, Leguan16 commented
Alright will do! I also like it way more than the current version.

2025-01-14 19:22 UTC, Leguan16 commented
> I like this implementation a lot more, thanks! One thing, could you please rename this `vanilla` within the ConfigDocBlock to something more like `showVanillaValue` or something slightly more self explanatory. Good to merge then

changed the param name.

2025-02-17 20:58 UTC, olijeffers0n approved these changes

2025-02-17 20:58 UTC, merged