Update velocity event.mdx
PaperMC/docs pull request #504
Opened 2024-12-05 21:35 UTC by KastenKlicker

Update event.mdx to remove deprecated velocity API usage.

2024-12-05 21:44 UTC, olijeffers0n approved these changes

2024-12-05 21:55 UTC, powercasgamer requested changes

2024-12-05 21:55 UTC, powercasgamer commented on docs/velocity/dev/api/event.mdx
> +Every listener has a <Javadoc name={"com.velocitypowered.api.event.Subscribe"} project={"velocity"}>`priority`</Javadoc>.
```suggestion
Every listener has a <Javadoc name={"com.velocitypowered.api.event.Subscribe#priority()"} project={"velocity"}>`priority`</Javadoc>.
```

2024-12-05 21:55 UTC, powercasgamer commented on docs/velocity/dev/api/event.mdx
> +Note that due to compatibility constraints, you must specify <Javadoc name={"com.velocitypowered.api.event.PostOrder"} project={"velocity"}>`PostOrder.CUSTOM`</Javadoc> in order to use this field.
```suggestion
:::note

Due to compatibility constraints, you must specify <Javadoc name={"com.velocitypowered.api.event.PostOrder"} project={"velocity"}>`PostOrder.CUSTOM`</Javadoc> in order to use this field.

:::
```
or maybe a warning 🤷

2024-12-05 22:14 UTC, zlataovce requested changes

2024-12-05 22:14 UTC, zlataovce commented on docs/velocity/dev/api/event.mdx
> +Due to compatibility constraints, you must specify <Javadoc name={"com.velocitypowered.api.event.PostOrder"} project={"velocity"}>`PostOrder.CUSTOM`</Javadoc> in order to use this field.
```suggestion
Due to compatibility constraints, you must specify <Javadoc name={"com.velocitypowered.api.event.PostOrder#CUSTOM"} project={"velocity"}>`PostOrder.CUSTOM`</Javadoc> in order to use this field.
```

2024-12-05 22:14 UTC, zlataovce commented on docs/velocity/dev/api/event.mdx
> +  @Subscribe(priority = 100,order = PostOrder.CUSTOM)
```suggestion
  @Subscribe(priority = 100, order = PostOrder.CUSTOM)
```

2024-12-05 22:14 UTC, zlataovce commented on docs/velocity/dev/api/event.mdx
> +  @Subscribe(priority = 100,order = PostOrder.CUSTOM)
```suggestion
  @Subscribe(priority = 100, order = PostOrder.CUSTOM)
```

2024-12-06 14:47 UTC, zlataovce approved these changes

2024-12-06 14:48 UTC, merged