Obfuscation Changes
PaperMC/docs pull request #515
Opened 2024-12-29 04:35 UTC by Owen1212055

2024-12-29 13:05 UTC, NoahvdAa requested changes

2024-12-29 13:05 UTC, NoahvdAa commented on config-specs/paper/paper-global.yml
> +            how items may look visually to other players.
```suggestion
            how items look to other players.
```

2024-12-29 13:05 UTC, NoahvdAa commented on config-specs/paper/paper-global.yml
> +              This may be useful if you want to hide certain components not important to other items.
```suggestion
              This may be useful if you want to hide certain components not important to other players.
```

2024-12-29 13:05 UTC, NoahvdAa commented on config-specs/paper/paper-global.yml
> +              Controls whether the items with the item model of `minecraft:elytra` count should be hidden from other players.
```suggestion
              Controls whether the item count for items with the item model of `minecraft:elytra` should be hidden from other players.
```

2024-12-29 13:19 UTC, zlataovce requested changes

2024-12-29 13:19 UTC, zlataovce commented on config-specs/paper/paper-global.yml
> +          default: []
```suggestion
          default: "[]"
```

2024-12-29 13:19 UTC, zlataovce commented on config-specs/paper/paper-global.yml
> +          default: ['minecraft:lodestone_tracker']
```suggestion
          default: "[minecraft:lodestone_tracker]"
```

2024-12-29 13:19 UTC, zlataovce commented on config-specs/paper/paper-global.yml
> +        default: false
```suggestion
        default: "false"
```

2024-12-29 13:19 UTC, zlataovce commented on config-specs/paper/paper-global.yml
> +            default: [ ]
```suggestion
            default: "[]"
```

2024-12-29 13:19 UTC, zlataovce commented on config-specs/paper/paper-global.yml
> +            default: [ minecraft:damage ]
```suggestion
            default: "[minecraft:damage]"
```

2025-01-07 20:43 UTC, zlataovce commented on config-specs/paper/paper-global.yml
> +          The hidden data components can be extended or reduced via the respective `also-obfuscate` and `dont-obfuscate` respectively.
```suggestion
          The hidden data components can be extended or reduced via `also-obfuscate` and `dont-obfuscate` respectively.
```

2025-01-07 20:54 UTC, zlataovce approved these changes

2025-01-08 16:06 UTC, olijeffers0n approved these changes

2025-01-09 17:58 UTC, merged